version: "3"
services:
  livekit:
    image: us-east1-docker.pkg.dev/ct-streaming-platform-dev/carbonteq-docker/livekit-server:0.1.0
    command: ["--config" ,"/livekit.yaml"]
    depends_on:
      - redis
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    volumes:
      - "$PWD/livekit.yaml:/livekit.yaml"
    restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
  egress:
    image: us-east1-docker.pkg.dev/ct-streaming-platform-dev/carbonteq-docker/egress:0.1.3
    env_file:
      - ./config.env
    depends_on:
      - livekit
    volumes:
      - "$PWD/config.yaml:/config.yaml"
